### ISSUE TITLE
FE - Create Webpages as per design with standard FE

### ISSUE THREAD

**Issue by raghavkhamar-stride** [strideai/FAQ_Generation_FE#1]
# Objective
# Tasks
- [ ] Designing all pages as per the wireframes
- [ ] Standard code behind
- [ ] Testing and integration
